adding dino
hackclub/dinosaurs pull request #313
Opened 2021-06-19 15:53 UTC by Mehak-Mehta

2021-06-19 16:06 UTC, sampoder requested changes
Please add a dino file :D

2021-06-19 16:14 UTC, Mehak-Mehta commented
I added the file :)

2021-06-20 01:06 UTC, sampoder commented
Could you please add it again? It isn't showing in this PR

2021-07-05 03:38 UTC, sampoder commented
Closing due to inactivity, feel free to let me know and I can reopen

2021-07-05 03:38 UTC, closed without merging