Added a really chill dino :tada:
hackclub/dinosaurs pull request #585
Opened 2022-10-09 15:13 UTC by markonije

Added a really chill dino :tada:

2022-10-09 23:18 UTC, exu3 requested changes
😎 cool! Could you add this dinosaur to the README please?

2022-10-10 16:47 UTC, markonije commented
Added it!
@exu3

2022-10-10 19:23 UTC, exu3 commented on README.md
> +![](/markonije_chill.png)
```suggestion
![](markonije_chill.png)
```

2022-10-10 19:23 UTC, exu3 approved these changes
very chill, thank you!

2022-10-10 19:24 UTC, merged