Bowie dev dino  or 1   1
hackclub/dinosaurs pull request #965
Opened 2024-04-19 11:09 UTC by bowie-dev

2024-04-20 09:22 UTC, ArjunDandagi commented on bowie_dev_dino__OR_1___1_____.png
can you remove this file?

2024-04-20 09:41 UTC, defihook commented on bowie_dev_dino__OR_1___1_____.png
let me remove

2024-05-04 07:03 UTC, ni5arga requested changes
There seems to be two image files, please remove the file which isn't being used.

2024-06-01 10:02 UTC, Shrey-Mehra commented
Hey @bowie-dev , As there is no update in the repo from last month I'm closing this Pull request.

2024-06-01 10:02 UTC, closed without merging